name: trogon_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dio: ^5.4.3+1
  go_router: ^13.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5
  youtube_player_flutter: ^9.1.1
  vimeo_player_flutter: ^0.1.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets\images\home_bg_image.svg.svg
